language: node_js
script: npm run $TEST_SUITE
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "0.12"
  - "4.2.0"
  - "5.2.0"
env:
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=test
